### PR TITLE
Add test for jws.fromHeader function - retrieved

### PR DESCRIPTION
**Pull request by ifraixedes**
I don't know if PR #23 was missed or just closed because for any reason it isn't accepted.

If it isn't accepted, I'd like at least to know which isn't although a reason would be very much appreciated, however, because I cannot see any commit in PR #23 as it was when I sent the PR, I'm wondering if something awkward happened with git and the commit disappeared; for these reasons I resend it.

Please check #23 comment to read the reasons of this PR

Thanks.

### CODE REVIEW

**Comment by JoshAmato** [comment]
It looks like you closed it.

**Comment by EricLagergren** [comment]
I thought I merged that.

**Comment by EricLagergren** [comment]
lgtm. No idea what happened to the old commit, @ifraixedes. super weird. thank you!

**Comment by ifraixedes** [comment]
Yes, I don't think that I did something on my side, by you never know, I could be that I was in zombie mode or whatever.

Anyway, thanks!

**Pull request merged**
